// ============================================================
// 한글 공부 - 학습 데이터
// ============================================================

const DATA = {
  // ── 1단계: 자음 ──
  consonants: [
    { char: 'ㄱ', roman: 'g/k', name: '기역', hint: '총(Gun) 모양 🔫' },
    { char: 'ㄴ', roman: 'n', name: '니은', hint: '의자 모양 🪑' },
    { char: 'ㄷ', roman: 'd/t', name: '디귿', hint: '문(Door) 모양 🚪' },
    { char: 'ㄹ', roman: 'r/l', name: '리을', hint: '꼬불꼬불 뱀 🐍' },
    { char: 'ㅁ', roman: 'm', name: '미음', hint: '네모 지도 🗺️' },
    { char: 'ㅂ', roman: 'b/p', name: '비읍', hint: '침대(Bed) 🛏️' },
    { char: 'ㅅ', roman: 's', name: '시옷', hint: '산타 모자 🎅' },
    { char: 'ㅇ', roman: 'ng/∅', name: '이응', hint: '동그라미 ⭕' },
    { char: 'ㅈ', roman: 'j', name: '지읒', hint: '주전자 🫖' },
    { char: 'ㅊ', roman: 'ch', name: '치읓', hint: '교회 지붕 ⛪' },
    { char: 'ㅋ', roman: 'k', name: '키읔', hint: '열쇠(Key) 🔑' },
    { char: 'ㅌ', roman: 't', name: '티읕', hint: '이빨(Teeth) 🦷' },
    { char: 'ㅍ', roman: 'p', name: '피읖', hint: '피아노 🎹' },
    { char: 'ㅎ', roman: 'h', name: '히읗', hint: '모자 쓴 사람 🎩' },
    { char: 'ㄲ', roman: 'kk', name: '쌍기역', hint: 'ㄱ 두 번! 더 세게 💪' },
    { char: 'ㄸ', roman: 'tt', name: '쌍디귿', hint: 'ㄷ 두 번! 더 세게 💪' },
    { char: 'ㅃ', roman: 'pp', name: '쌍비읍', hint: 'ㅂ 두 번! 더 세게 💪' },
    { char: 'ㅆ', roman: 'ss', name: '쌍시옷', hint: 'ㅅ 두 번! 더 세게 💪' },
    { char: 'ㅉ', roman: 'jj', name: '쌍지읒', hint: 'ㅈ 두 번! 더 세게 💪' },
  ],

  // ── 2단계: 모음 (ㅐ/ㅔ, 왜/웨 등 헷갈리는 모음 강화) ──
  vowels: [
    { char: 'ㅏ', roman: 'a', name: '아', hint: '오른쪽 획 → 아! 👶' },
    { char: 'ㅑ', roman: 'ya', name: '야', hint: 'ㅏ에 획 추가 → 야! 🎉' },
    { char: 'ㅓ', roman: 'eo', name: '어', hint: '왼쪽 획 ← 어? 🤔' },
    { char: 'ㅕ', roman: 'yeo', name: '여', hint: 'ㅓ에 획 추가 → 여! 🦄' },
    { char: 'ㅗ', roman: 'o', name: '오', hint: '위로 ↑ 오! 🌞' },
    { char: 'ㅛ', roman: 'yo', name: '요', hint: 'ㅗ에 획 추가 → 요! 🧸' },
    { char: 'ㅜ', roman: 'u', name: '우', hint: '아래로 ↓ 우~ 🌧️' },
    { char: 'ㅠ', roman: 'yu', name: '유', hint: 'ㅜ에 획 추가 → 유! 🎈' },
    { char: 'ㅡ', roman: 'eu', name: '으', hint: '가로 줄 ─ 으.. ➖' },
    { char: 'ㅣ', roman: 'i', name: '이', hint: '세로 줄 │ 이! 🌳' },
    // ── 헷갈리는 모음 집중 ──
    { char: 'ㅐ', roman: 'ae', name: '애', hint: '⚠️ ㅏ+ㅣ → "에"와 거의 같은 소리! 🍎' },
    { char: 'ㅔ', roman: 'e', name: '에', hint: '⚠️ ㅓ+ㅣ → "애"와 거의 같은 소리! 🥚' },
    { char: 'ㅒ', roman: 'yae', name: '얘', hint: '⚠️ ㅑ+ㅣ → 얘기할 때의 "얘" 💬' },
    { char: 'ㅖ', roman: 'ye', name: '예', hint: '⚠️ ㅕ+ㅣ → 예/네 할 때의 "예" ✋' },
    { char: 'ㅘ', roman: 'wa', name: '와', hint: 'ㅗ+ㅏ = 와! 🌈' },
    { char: 'ㅙ', roman: 'wae', name: '왜', hint: '⚠️ ㅗ+ㅐ = 왜? (why) ❓' },
    { char: 'ㅚ', roman: 'oe', name: '외', hint: 'ㅗ+ㅣ = 외 (outside) 🚪' },
    { char: 'ㅝ', roman: 'wo', name: '워', hint: 'ㅜ+ㅓ = 워~ 🐺' },
    { char: 'ㅞ', roman: 'we', name: '웨', hint: '⚠️ ㅜ+ㅔ = 웨 → "왜"와 같은 소리! 🔔' },
    { char: 'ㅟ', roman: 'wi', name: '위', hint: 'ㅜ+ㅣ = 위 (up) ⬆️' },
    { char: 'ㅢ', roman: 'ui', name: '의', hint: 'ㅡ+ㅣ = 의 (of) 📎' },
  ],

  // ── 4단계: 단어 (대폭 확장 + 받침/쌍자음/헷갈리는 모음 집중) ──
  words: {
    인사: [
      { kr: '안녕', en: 'Hello', emoji: '👋' },
      { kr: '감사', en: 'Thanks', emoji: '🙏' },
      { kr: '네', en: 'Yes', emoji: '✅' },
      { kr: '아니요', en: 'No', emoji: '❌' },
      { kr: '사랑', en: 'Love', emoji: '❤️' },
      { kr: '반갑다', en: 'Nice to meet', emoji: '🤝' },
      { kr: '미안', en: 'Sorry', emoji: '😢' },
      { kr: '괜찮아', en: "It's OK", emoji: '👌' },
      { kr: '잘 자', en: 'Good night', emoji: '🌙' },
      { kr: '축하', en: 'Congrats', emoji: '🎊' },
    ],
    가족: [
      { kr: '엄마', en: 'Mom', emoji: '👩' },
      { kr: '아빠', en: 'Dad', emoji: '👨' },
      { kr: '언니', en: 'Older sister', emoji: '👧' },
      { kr: '오빠', en: 'Older brother', emoji: '👦' },
      { kr: '동생', en: 'Younger sibling', emoji: '🧒' },
      { kr: '누나', en: 'Older sister (m)', emoji: '👩‍🦰' },
      { kr: '형', en: 'Older brother (m)', emoji: '🧑' },
      { kr: '할머니', en: 'Grandma', emoji: '👵' },
      { kr: '할아버지', en: 'Grandpa', emoji: '👴' },
      { kr: '아기', en: 'Baby', emoji: '👶' },
      { kr: '부모님', en: 'Parents', emoji: '👨‍👩‍👧' },
    ],
    음식: [
      { kr: '밥', en: 'Rice', emoji: '🍚' },
      { kr: '물', en: 'Water', emoji: '💧' },
      { kr: '사과', en: 'Apple', emoji: '🍎' },
      { kr: '우유', en: 'Milk', emoji: '🥛' },
      { kr: '빵', en: 'Bread', emoji: '🍞' },
      { kr: '김치', en: 'Kimchi', emoji: '🥬' },
      { kr: '떡', en: 'Rice cake', emoji: '🍡' },
      { kr: '국', en: 'Soup', emoji: '🍲' },
      { kr: '고기', en: 'Meat', emoji: '🥩' },
      { kr: '달걀', en: 'Egg', emoji: '🥚' },
      { kr: '과자', en: 'Snack', emoji: '🍪' },
      { kr: '딸기', en: 'Strawberry', emoji: '🍓' },
      { kr: '바나나', en: 'Banana', emoji: '🍌' },
      { kr: '수박', en: 'Watermelon', emoji: '🍉' },
      { kr: '포도', en: 'Grape', emoji: '🍇' },
      { kr: '라면', en: 'Ramen', emoji: '🍜' },
      { kr: '치킨', en: 'Chicken', emoji: '🍗' },
      { kr: '피자', en: 'Pizza', emoji: '🍕' },
      { kr: '아이스크림', en: 'Ice cream', emoji: '🍦' },
      { kr: '케이크', en: 'Cake', emoji: '🎂' },
    ],
    동물: [
      { kr: '강아지', en: 'Puppy', emoji: '🐶' },
      { kr: '고양이', en: 'Cat', emoji: '🐱' },
      { kr: '토끼', en: 'Rabbit', emoji: '🐰' },
      { kr: '새', en: 'Bird', emoji: '🐦' },
      { kr: '곰', en: 'Bear', emoji: '🐻' },
      { kr: '코끼리', en: 'Elephant', emoji: '🐘' },
      { kr: '사자', en: 'Lion', emoji: '🦁' },
      { kr: '호랑이', en: 'Tiger', emoji: '🐯' },
      { kr: '원숭이', en: 'Monkey', emoji: '🐵' },
      { kr: '돼지', en: 'Pig', emoji: '🐷' },
      { kr: '닭', en: 'Chicken', emoji: '🐔' },
      { kr: '물고기', en: 'Fish', emoji: '🐟' },
      { kr: '거북이', en: 'Turtle', emoji: '🐢' },
      { kr: '뱀', en: 'Snake', emoji: '🐍' },
      { kr: '개구리', en: 'Frog', emoji: '🐸' },
    ],
    신체: [
      { kr: '머리', en: 'Head', emoji: '🧠' },
      { kr: '눈', en: 'Eye', emoji: '👁️' },
      { kr: '코', en: 'Nose', emoji: '👃' },
      { kr: '입', en: 'Mouth', emoji: '👄' },
      { kr: '귀', en: 'Ear', emoji: '👂' },
      { kr: '손', en: 'Hand', emoji: '✋' },
      { kr: '발', en: 'Foot', emoji: '🦶' },
      { kr: '팔', en: 'Arm', emoji: '💪' },
      { kr: '다리', en: 'Leg', emoji: '🦵' },
      { kr: '배', en: 'Belly', emoji: '🤰' },
      { kr: '목', en: 'Neck', emoji: '🦒' },
      { kr: '이', en: 'Tooth', emoji: '🦷' },
    ],
    자연: [
      { kr: '하늘', en: 'Sky', emoji: '🌤️' },
      { kr: '바다', en: 'Sea', emoji: '🌊' },
      { kr: '산', en: 'Mountain', emoji: '⛰️' },
      { kr: '나무', en: 'Tree', emoji: '🌳' },
      { kr: '꽃', en: 'Flower', emoji: '🌸' },
      { kr: '별', en: 'Star', emoji: '⭐' },
      { kr: '달', en: 'Moon', emoji: '🌙' },
      { kr: '해', en: 'Sun', emoji: '☀️' },
      { kr: '비', en: 'Rain', emoji: '🌧️' },
      { kr: '눈', en: 'Snow', emoji: '❄️' },
      { kr: '바람', en: 'Wind', emoji: '💨' },
      { kr: '구름', en: 'Cloud', emoji: '☁️' },
      { kr: '강', en: 'River', emoji: '🏞️' },
      { kr: '불', en: 'Fire', emoji: '🔥' },
      { kr: '돌', en: 'Stone', emoji: '🪨' },
      { kr: '흙', en: 'Soil', emoji: '🟤' },
    ],
    장소: [
      { kr: '집', en: 'House', emoji: '🏠' },
      { kr: '학교', en: 'School', emoji: '🏫' },
      { kr: '병원', en: 'Hospital', emoji: '🏥' },
      { kr: '가게', en: 'Store', emoji: '🏪' },
      { kr: '공원', en: 'Park', emoji: '🌳' },
      { kr: '은행', en: 'Bank', emoji: '🏦' },
      { kr: '역', en: 'Station', emoji: '🚉' },
      { kr: '회사', en: 'Company', emoji: '🏢' },
      { kr: '식당', en: 'Restaurant', emoji: '🍽️' },
      { kr: '도서관', en: 'Library', emoji: '📚' },
    ],
    물건: [
      { kr: '가방', en: 'Bag', emoji: '🎒' },
      { kr: '책', en: 'Book', emoji: '📖' },
      { kr: '연필', en: 'Pencil', emoji: '✏️' },
      { kr: '의자', en: 'Chair', emoji: '🪑' },
      { kr: '시계', en: 'Clock', emoji: '⏰' },
      { kr: '전화', en: 'Phone', emoji: '📱' },
      { kr: '컴퓨터', en: 'Computer', emoji: '💻' },
      { kr: '열쇠', en: 'Key', emoji: '🔑' },
      { kr: '우산', en: 'Umbrella', emoji: '☂️' },
      { kr: '안경', en: 'Glasses', emoji: '👓' },
      { kr: '옷', en: 'Clothes', emoji: '👕' },
      { kr: '신발', en: 'Shoes', emoji: '👟' },
      { kr: '모자', en: 'Hat', emoji: '🧢' },
    ],
    동작: [
      { kr: '가다', en: 'Go', emoji: '🚶' },
      { kr: '오다', en: 'Come', emoji: '🏃' },
      { kr: '먹다', en: 'Eat', emoji: '🍽️' },
      { kr: '마시다', en: 'Drink', emoji: '🥤' },
      { kr: '자다', en: 'Sleep', emoji: '😴' },
      { kr: '보다', en: 'See/Watch', emoji: '👀' },
      { kr: '듣다', en: 'Listen', emoji: '👂' },
      { kr: '말하다', en: 'Speak', emoji: '🗣️' },
      { kr: '읽다', en: 'Read', emoji: '📖' },
      { kr: '쓰다', en: 'Write', emoji: '✍️' },
      { kr: '놀다', en: 'Play', emoji: '🎮' },
      { kr: '웃다', en: 'Laugh', emoji: '😄' },
      { kr: '울다', en: 'Cry', emoji: '😢' },
      { kr: '걷다', en: 'Walk', emoji: '🚶‍♂️' },
      { kr: '뛰다', en: 'Run/Jump', emoji: '🏃‍♂️' },
      { kr: '앉다', en: 'Sit', emoji: '🪑' },
      { kr: '서다', en: 'Stand', emoji: '🧍' },
    ],
    색깔: [
      { kr: '빨강', en: 'Red', emoji: '🔴' },
      { kr: '파랑', en: 'Blue', emoji: '🔵' },
      { kr: '노랑', en: 'Yellow', emoji: '🟡' },
      { kr: '초록', en: 'Green', emoji: '🟢' },
      { kr: '하양', en: 'White', emoji: '⚪' },
      { kr: '까망', en: 'Black', emoji: '⚫' },
      { kr: '분홍', en: 'Pink', emoji: '🩷' },
      { kr: '보라', en: 'Purple', emoji: '🟣' },
    ],
    숫자: [
      { kr: '하나', en: 'One', emoji: '1️⃣' },
      { kr: '둘', en: 'Two', emoji: '2️⃣' },
      { kr: '셋', en: 'Three', emoji: '3️⃣' },
      { kr: '넷', en: 'Four', emoji: '4️⃣' },
      { kr: '다섯', en: 'Five', emoji: '5️⃣' },
      { kr: '여섯', en: 'Six', emoji: '6️⃣' },
      { kr: '일곱', en: 'Seven', emoji: '7️⃣' },
      { kr: '여덟', en: 'Eight', emoji: '8️⃣' },
      { kr: '아홉', en: 'Nine', emoji: '9️⃣' },
      { kr: '열', en: 'Ten', emoji: '🔟' },
    ],
    // ── 받침 집중 단어 ──
    '받침ㄱ': [
      { kr: '국', en: 'Soup', emoji: '🍲' },
      { kr: '약', en: 'Medicine', emoji: '💊' },
      { kr: '책', en: 'Book', emoji: '📖' },
      { kr: '먹', en: 'Eat (stem)', emoji: '🍽️' },
      { kr: '학', en: 'Study', emoji: '📚' },
      { kr: '족', en: 'Foot/Clan', emoji: '🦶' },
      { kr: '숙', en: 'Sleep/Stay', emoji: '🏨' },
    ],
    '받침ㄴ': [
      { kr: '눈', en: 'Eye/Snow', emoji: '👁️' },
      { kr: '손', en: 'Hand', emoji: '✋' },
      { kr: '산', en: 'Mountain', emoji: '⛰️' },
      { kr: '문', en: 'Door', emoji: '🚪' },
      { kr: '돈', en: 'Money', emoji: '💰' },
      { kr: '인', en: 'Person', emoji: '🧑' },
      { kr: '반', en: 'Class/Half', emoji: '🏫' },
    ],
    '받침ㄹ': [
      { kr: '발', en: 'Foot', emoji: '🦶' },
      { kr: '달', en: 'Moon', emoji: '🌙' },
      { kr: '별', en: 'Star', emoji: '⭐' },
      { kr: '말', en: 'Word/Horse', emoji: '🐴' },
      { kr: '길', en: 'Road', emoji: '🛤️' },
      { kr: '술', en: 'Alcohol', emoji: '🍶' },
      { kr: '볼', en: 'Cheek/Ball', emoji: '⚽' },
    ],
    '받침ㅁ': [
      { kr: '곰', en: 'Bear', emoji: '🐻' },
      { kr: '봄', en: 'Spring', emoji: '🌸' },
      { kr: '밤', en: 'Night/Chestnut', emoji: '🌙' },
      { kr: '남', en: 'South/Man', emoji: '🧭' },
      { kr: '김', en: 'Seaweed/Kim', emoji: '🍣' },
      { kr: '감', en: 'Persimmon', emoji: '🍊' },
      { kr: '꿈', en: 'Dream', emoji: '💭' },
    ],
    '받침ㅂ': [
      { kr: '밥', en: 'Rice', emoji: '🍚' },
      { kr: '집', en: 'House', emoji: '🏠' },
      { kr: '입', en: 'Mouth', emoji: '👄' },
      { kr: '잎', en: 'Leaf', emoji: '🍃' },
      { kr: '숲', en: 'Forest', emoji: '🌲' },
      { kr: '법', en: 'Law', emoji: '⚖️' },
      { kr: '십', en: 'Ten', emoji: '🔟' },
    ],
    '받침ㅇ': [
      { kr: '강', en: 'River', emoji: '🏞️' },
      { kr: '공', en: 'Ball', emoji: '⚽' },
      { kr: '방', en: 'Room', emoji: '🛏️' },
      { kr: '동', en: 'East/Copper', emoji: '🧭' },
      { kr: '형', en: 'Brother', emoji: '🧑' },
      { kr: '빵', en: 'Bread', emoji: '🍞' },
      { kr: '정', en: 'Affection', emoji: '💕' },
    ],
    // ── 쌍자음 단어 ──
    쌍자음: [
      { kr: '빠르다', en: 'Fast', emoji: '⚡' },
      { kr: '아빠', en: 'Dad', emoji: '👨' },
      { kr: '오빠', en: 'Brother', emoji: '👦' },
      { kr: '뼈', en: 'Bone', emoji: '🦴' },
      { kr: '예쁘다', en: 'Pretty', emoji: '🌹' },
      { kr: '쓰다', en: 'Write/Bitter', emoji: '✍️' },
      { kr: '쌀', en: 'Rice (raw)', emoji: '🌾' },
      { kr: '싸다', en: 'Cheap/Wrap', emoji: '💰' },
      { kr: '쓰레기', en: 'Trash', emoji: '🗑️' },
      { kr: '끄다', en: 'Turn off', emoji: '📴' },
      { kr: '까다', en: 'Peel', emoji: '🍌' },
      { kr: '꼬리', en: 'Tail', emoji: '🐕' },
      { kr: '꽃', en: 'Flower', emoji: '🌸' },
      { kr: '꿈', en: 'Dream', emoji: '💭' },
      { kr: '떡', en: 'Rice cake', emoji: '🍡' },
      { kr: '딸기', en: 'Strawberry', emoji: '🍓' },
      { kr: '뜨겁다', en: 'Hot', emoji: '🔥' },
      { kr: '짜다', en: 'Salty/Squeeze', emoji: '🧂' },
      { kr: '찌개', en: 'Stew', emoji: '🍲' },
      { kr: '짧다', en: 'Short', emoji: '📏' },
    ],
    // ── ㅐ/ㅔ 헷갈리는 단어 ──
    'ㅐ vs ㅔ': [
      { kr: '개', en: 'Dog', emoji: '🐕' },
      { kr: '게', en: 'Crab', emoji: '🦀' },
      { kr: '배', en: 'Belly/Pear/Ship', emoji: '🚢' },
      { kr: '베다', en: 'Cut/Lay pillow', emoji: '🔪' },
      { kr: '내', en: 'My/Stream', emoji: '🏞️' },
      { kr: '네', en: 'Yes/Your', emoji: '✅' },
      { kr: '세다', en: 'Strong/Count', emoji: '💪' },
      { kr: '새', en: 'Bird/New', emoji: '🐦' },
      { kr: '대', en: 'Bamboo/Big', emoji: '🎋' },
      { kr: '데', en: 'Place', emoji: '📍' },
      { kr: '해', en: 'Sun/Do', emoji: '☀️' },
      { kr: '혜', en: 'Grace/Favor', emoji: '🎁' },
      { kr: '매', en: 'Hawk/Every', emoji: '🦅' },
      { kr: '메다', en: 'Carry (shoulder)', emoji: '🎒' },
    ],
    // ── 왜/웨/외 헷갈리는 단어 ──
    '왜 vs 웨': [
      { kr: '왜', en: 'Why', emoji: '❓' },
      { kr: '웨딩', en: 'Wedding', emoji: '💒' },
      { kr: '외국', en: 'Foreign country', emoji: '🌍' },
      { kr: '왼쪽', en: 'Left side', emoji: '⬅️' },
      { kr: '돼지', en: 'Pig', emoji: '🐷' },
      { kr: '되다', en: 'Become', emoji: '🔄' },
      { kr: '쇠', en: 'Iron/Metal', emoji: '⚙️' },
      { kr: '괜찮다', en: "It's OK", emoji: '👌' },
      { kr: '쉬다', en: 'Rest', emoji: '😌' },
      { kr: '취미', en: 'Hobby', emoji: '🎯' },
    ],
    // ── 시간/날씨 ──
    일상: [
      { kr: '오늘', en: 'Today', emoji: '📅' },
      { kr: '내일', en: 'Tomorrow', emoji: '📆' },
      { kr: '어제', en: 'Yesterday', emoji: '⏪' },
      { kr: '아침', en: 'Morning', emoji: '🌅' },
      { kr: '점심', en: 'Lunch', emoji: '🍱' },
      { kr: '저녁', en: 'Evening', emoji: '🌆' },
      { kr: '친구', en: 'Friend', emoji: '👫' },
      { kr: '선생님', en: 'Teacher', emoji: '👩‍🏫' },
      { kr: '학생', en: 'Student', emoji: '🧑‍🎓' },
      { kr: '공부', en: 'Study', emoji: '📝' },
      { kr: '일', en: 'Work/One', emoji: '💼' },
      { kr: '놀이', en: 'Play', emoji: '🎠' },
    ],
  },

  // ── 5단계: 받아쓰기 ──
  dictation: {
    easy: [
      '가','나','다','라','마','바','사','아','자','차','카','타','파','하',
      '개','게','배','새','해','왜',
    ],
    medium: [
      '사과','학교','가방','나무','바다','하늘','토끼','우유','김치',
      '엄마','아빠','동생','친구','공부','꽃','떡','쌀','빵','꿈',
      '강아지','고양이','딸기','외국','병원','선생님',
      '손','눈','발','별','집','방','곰','강','밤','국',
    ],
    hard: [
      '안녕하세요','감사합니다','사랑해요','좋은 아침','잘 자요','맛있어요',
      '괜찮아요','예쁘다','뜨겁다','빠르다','재미있어요',
    ],
  },

  cheers: ['잘했어요! 👏','대단해요! 🌟','최고예요! 🏆','멋져요! ✨','훌륭해요! 🎉','완벽해요! 💯'],
  retry: ['다시 해봐요! 💪','괜찮아요! 🌈','힘내요! 🌟','할 수 있어요! 🦋'],
};

// ── 한글 자모 분해/조합 ──
const HG = {
  I: ['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'],
  M: ['ㅏ','ㅐ','ㅑ','ㅒ','ㅓ','ㅔ','ㅕ','ㅖ','ㅗ','ㅘ','ㅙ','ㅚ','ㅛ','ㅜ','ㅝ','ㅞ','ㅟ','ㅠ','ㅡ','ㅢ','ㅣ'],
  F: ['','ㄱ','ㄲ','ㄳ','ㄴ','ㄵ','ㄶ','ㄷ','ㄹ','ㄺ','ㄻ','ㄼ','ㄽ','ㄾ','ㄿ','ㅀ','ㅁ','ㅂ','ㅄ','ㅅ','ㅆ','ㅇ','ㅈ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'],

  decompose(ch) {
    const c = ch.charCodeAt(0) - 0xAC00;
    if (c < 0 || c > 11171) return null;
    return { i: this.I[~~(c/588)], m: this.M[~~((c%588)/28)], f: this.F[c%28] || null };
  },
  compose(i, m, f) {
    const ii = this.I.indexOf(i), mm = this.M.indexOf(m), ff = f ? this.F.indexOf(f) : 0;
    if (ii < 0 || mm < 0 || ff < 0) return '';
    return String.fromCharCode(0xAC00 + ii*588 + mm*28 + ff);
  },
  isSyllable(ch) { const c = ch.charCodeAt(0); return c >= 0xAC00 && c <= 0xD7A3; },
};
